version: "3"
services:
  metadata-connector:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/metadata-connector:1.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=test.52north.org
