version: "3"
services:
  metadata-connector:
    build:
      context: .
    image: wacodis/metadata-connector:latest
    ports:
      - 8080:8080
    environment: 
      - SPRING_RABBITMQ_HOST=host.docker.internal
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=rabbitmq
      - SPRING_CLOUD_STREAM_BINDINGS_INPUTDATAENVELOPE_DESTINATION=wacodis.test.data.available
      - DATAACCESS_URI=http://host.docker.internal:8082/dataAccess