version: "3"
services:
  metadata-connector:
    build:
      context: .
    image: wacodis/metadata-connector:1.0.1
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=test.52north.org
